trigger:
- master

variables:
  # Azure service connection established during pipeline creation
  azureSubscription: Visual Studio Enterprise – MPN
  appName: my-app-name01
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

- task: AzureWebApp@1 # Add this at the end of your file
  inputs:
    azureSubscription: <Azure service connection>
    appType: webAppLinux
    appName: $(appName)
    package: $(System.ArtifactsDirectory)/**/*.zip